version: "3.7"

networks:
  appnet:
    ipam:
      driver: default
      config:
        - subnet: 12.0.0.0/24

services:
  backend:
    image: mahendrshinde/back-end:latest
    ports:
      - "9000:8080"
    networks:
    - appnet

  frontend:
    image: mahendrshinde/front-end:latest
    ports:
    - "8080:80"
    networks:
    - appnet